### ISSUE TITLE
 The container won't start

### ISSUE THREAD

**Issue by akadorkin** [IzeBerg/go-tribute-payments-hook#1]
When I check the logs of the container, I see this:

panic: telegram_api_id: strconv.ParseInt: parsing "": invalid syntax ()

```
goroutine 1 [running]:
go-tribute-api/settings.parseInt64({0x89358f, 0xf}, {0x0, 0x0})
 /build/settings/settings.go:16 +0x125
go-tribute-api/settings.init()
 /build/settings/settings.go:30 +0x4b
```
Also, there is no settings.py file anywhere. How do I start the container?

**Comment by izeberg** [comment]
Please read the Settings section:
https://github.com/izeberg/go-tribute-payments-hook?tab=readme-ov-file#settings

It won't start until you configure telegram settings
